# Generated by Django 4.0.5 on 2022-07-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geolocation',
            name='signup_date',
            field=models.DateField(default=29),
        ),
    ]
